### ISSUE TITLE
can your code only apply to 2D mesh? How to achieve this?

### ISSUE THREAD

**Issue by universewill** [cheind/mesh-deform#1]
I want to apply deform to 2D mesh, how to achieve this?

Besides, how to compile without open-mesh, osg and Sophus? Are they enssential to 2D mesh deform?

**Comment by cheind** [comment]
You could try to put the 2D mesh on the xy-plane at z=0. Then after each iteration perform a projection onto z=0. 

I have not yet compiled without the libraries you mention. I'd say they are more or less essential.
